### ISSUE TITLE
What is the PCA matrix in the Youtube-8M feature extraction process?

### ISSUE THREAD

**Issue by wikipedia2008** [wangheda/youtube-8m#1]
我没仔细看代码，但是很好奇，Google怎么没开放inception3提取特征向量之后，进行pca降维的特征矩阵，是需要开发者自己计算吗？
谢谢

**Comment by wangheda** [comment]
@wikipedia2008 
There were heated discussions on the Google Groups forum of this dataset about whether Google will make the feature extraction process of this dataset public, and whether the original frames can be made public.

At that time the official answer is no, since this may advantage those who has more computation power and video data. 

Since this competition is over now. You can ask the organizers at Google Research about whether the raw data can be made public.

**Comment by wangheda** [comment]
@wikipedia2008 
Hi, just let you know that the PCA matrix along with the feature extraction process has been made public.
Check [this GitHub page](https://github.com/google/youtube-8m/blob/master/feature_extractor/feature_extractor.py) for details.
