### ISSUE TITLE
Is there any pre-trained models about the Youtube-8M dataset?

### ISSUE THREAD

**Issue by wikipedia2008** [wangheda/youtube-8m#2]
你好，heda，我查看了竞赛的论文和code，但是没发现有训练好的pb模型，我个人实在没有GPU资源去训练，但是又想尝试结果，imagenet的模型都是开放的，youtube-8m不开放吗？

打扰大神了

**Comment by wangheda** [comment]
Since the source code and the data set are both open to the public, the trained models are surely also open to the public. But we don't have the resources to host the models, as the files are quite large (about 3GB each).

But what's really in the way of predicting on new videos is that Google hasn't publish the feature extraction process. There has been many posts calling for the process to be made public in [this forum](https://groups.google.com/forum/#!forum/youtube8m-users).

**Comment by wangheda** [comment]
@wikipedia2008 
Hi, since the competition host has already made the feature extraction process available. It seems the model we trained can be applied to new videos now. 

The model checkpoints are so large that we delete many of them. But we still have a few of the model checkpoints left, and will make them public upon request.
